version: '3.1'
services:
  application:
    container_name: openjdk-17-slim
    image: openjdk:17-slim
    restart: always
    command: "tail -f /dev/null"
    ports:
      - "8000:8000"

  db:
    container_name: mysql-8.0.37-oracle
    image: mysql:8.0.37-oracle
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    ports:
      - "3306:3306"

